M48
; DRILL file {KiCad (6.0.4-0)} date Thursday, August 25, 2022 at 05:13:25 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-25T17:13:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X22.102Y-40.755
X22.102Y-45.605
T2
X19.072Y-40.455
X19.072Y-45.905
T0
M30
